from fastapi import HTTPException, status, Depends, APIRouter
from sqlalchemy import select
from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError
from app.services.auth_service import get_password_hash
from app.core.database import get_db
from app.models.user import User
from app.schemas.user_auth_schema import CreateUserRequest

router = APIRouter(prefix="/users", tags=['Users'])


@router.post("/", status_code=status.HTTP_201_CREATED, response_model=User)
def create_user(user: CreateUserRequest, db: Session = Depends(get_db)):
    try: 
        password_hash = get_password_hash(user.password)
        new_user = User(
            email=user.email,
            password=password_hash
        )
        db.add(new_user)
        db.commit()
        db.refresh() # LOADS AUTOGENERATED FIELDS
        return new_user
    except IntegrityError:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"User with email '{user.email}' already exists"
        )
    except Exception as error:
        print("Failed to create user", error)
        return error