from fastapi import HTTPException, status, Depends, APIRouter
from sqlalchemy import select
from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError
from app.services.auth_service import get_password_hash
from app.core.database import get_db
from app.models.user import User
from app.schemas.user_auth_schema import CreateUserRequest, UserInDB

user_router = APIRouter(prefix="/users", tags=['Users'])


@user_router.post("", status_code=status.HTTP_201_CREATED, response_model=UserInDB)
def create_user(user: CreateUserRequest, db: Session = Depends(get_db)) -> UserInDB:
    try: 
        password_hash = get_password_hash(user.password)
        new_user = User(
            email=user.email,
            hashed_password=password_hash
        )
        db.add(new_user)
        db.commit()
        db.refresh(user) # LOADS AUTOGENERATED FIELDS
        return new_user
    except IntegrityError:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"User with email '{user.email}' already exists"
        )
    except Exception as error:
        print("Failed to create user", error)
        return error



@user_router.get("/{id}", response_model=UserInDB)
def get_user(id: int, db: Session = Depends(get_db)) -> UserInDB:
    result = select(User).where(User.id == id)
    target_user = db.query(result).first()
    if target_user is None:
      raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"user with id: {id} was not found")
    return  target_user