"""
USER ORM model.

Each row in the 'users' table represents a user in our DOCIND system.
"""
from typing import List
from datetime import datetime
from sqlalchemy import Integer, String, DateTime, func, TIMESTAMP
from sqlalchemy.orm import Mapped, mapped_column
from pgvector.sqlalchemy import Vector
from app.core.database import Base


class User(Base):
    __tablename__="users"

    id: Mapped[str] = mapped_column(
            Integer,
            primary_key=True,
            autoincrement=True,
        )

    email: Mapped[str] = mapped_column(String, unique=True)
    hashed_password: Mapped[str] = mapped_column(String(512), nullable=False) 
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        server_default=func.now(), # generated by postgre
        nullable=False
    )